import { Prisma } from '@prisma/client';

import { prisma } from '@/lib/db';

/**
 * Operator-editable system settings.
 *
 * Secrets NEVER live here — they stay in environment variables. This table
 * holds only operational toggles and copy that an administrator may change
 * without a redeploy.
 */

export interface SystemSettings {
  applicationName: string;
  supportEmail: string;
  demoModeEnabled: boolean;
  freePreviewEnabled: boolean;
  maxCrawlPagesHardLimit: number;
  maintenanceBannerEnabled: boolean;
  maintenanceBannerText: string;
  llmEnhancementEnabled: boolean;
  searchObservationsEnabled: boolean;
  legalTemplateWarningEnabled: boolean;
  defaultReportFooter: string;
  signupsEnabled: boolean;
}

export const DEFAULT_SETTINGS: SystemSettings = {
  applicationName: 'RankInAI',
  supportEmail: 'support@rankinai.com',
  demoModeEnabled: true,
  freePreviewEnabled: true,
  maxCrawlPagesHardLimit: 50,
  maintenanceBannerEnabled: false,
  maintenanceBannerText: '',
  llmEnhancementEnabled: true,
  searchObservationsEnabled: true,
  legalTemplateWarningEnabled: true,
  defaultReportFooter: 'Generated by RankInAI — AI visibility and GEO audit platform.',
  signupsEnabled: true,
};

export const SETTINGS_KEY = 'app.settings';

export const SETTINGS_DESCRIPTIONS: Record<keyof SystemSettings, string> = {
  applicationName: 'Name shown in the interface, emails and report footers.',
  supportEmail: 'Address shown to customers for support enquiries.',
  demoModeEnabled: 'Show the instant sample demo on the marketing site.',
  freePreviewEnabled: 'Allow anonymous visitors to run the limited homepage preview.',
  maxCrawlPagesHardLimit: 'Absolute ceiling on pages crawled per audit, regardless of plan.',
  maintenanceBannerEnabled: 'Display a site-wide maintenance notice.',
  maintenanceBannerText: 'Text of the maintenance notice.',
  llmEnhancementEnabled:
    'Allow optional LLM narrative enhancement when OPENAI_API_KEY is configured. Audit scoring is always rule-based.',
  searchObservationsEnabled:
    'Allow optional public-web search observations when a search provider is configured.',
  legalTemplateWarningEnabled:
    'Show the reminder that legal pages are software-generated starting templates.',
  defaultReportFooter: 'Footer line printed on generated PDF reports.',
  signupsEnabled: 'Allow new account registration.',
};

let cache: { value: SystemSettings; expiresAt: number } | null = null;
const CACHE_TTL_MS = 15_000;

export async function getSettings(): Promise<SystemSettings> {
  if (cache && cache.expiresAt > Date.now()) return cache.value;

  try {
    const row = await prisma.systemSetting.findUnique({ where: { key: SETTINGS_KEY } });
    const stored = (row?.value ?? {}) as Partial<SystemSettings>;
    const merged: SystemSettings = { ...DEFAULT_SETTINGS, ...stored };
    cache = { value: merged, expiresAt: Date.now() + CACHE_TTL_MS };
    return merged;
  } catch {
    // A settings read must never take the site down.
    return DEFAULT_SETTINGS;
  }
}

export async function updateSettings(
  patch: Partial<SystemSettings>,
  updatedById: string,
): Promise<SystemSettings> {
  const current = await getSettings();
  const next: SystemSettings = { ...current, ...patch };

  // Never let an operator raise the crawl ceiling beyond what the plans allow.
  next.maxCrawlPagesHardLimit = Math.max(1, Math.min(50, next.maxCrawlPagesHardLimit));

  await prisma.systemSetting.upsert({
    where: { key: SETTINGS_KEY },
    create: {
      key: SETTINGS_KEY,
      value: next as unknown as Prisma.InputJsonValue,
      description: 'Operator-editable application settings.',
      updatedById,
    },
    update: {
      value: next as unknown as Prisma.InputJsonValue,
      updatedById,
    },
  });

  cache = { value: next, expiresAt: Date.now() + CACHE_TTL_MS };
  return next;
}

export function invalidateSettingsCache(): void {
  cache = null;
}
