import PDFDocument from 'pdfkit';

import { HORIZON_LABELS } from '@/lib/audit/recommendations';
import { overallScoreInterpretation } from '@/lib/audit/scoring';
import { SEVERITY_LABELS } from '@/lib/audit/types';
import { METHODOLOGY_SUMMARY, REPORT_LIMITATIONS, type ReportData } from '@/lib/report/types';
import { formatDate, scoreBandLabel } from '@/lib/utils';

/**
 * PDF report generation.
 *
 * Uses PDFKit with the built-in Helvetica family rather than a headless
 * browser: it runs anywhere Node runs, needs no Chromium binary on Railway, has
 * no persistent-disk dependency, and produces a deterministic document.
 *
 * Page breaks, headers, footers and page numbers are managed explicitly so no
 * component is ever cut in half.
 */

const PAGE = { width: 595.28, height: 841.89 }; // A4 in points
const MARGIN = { top: 64, bottom: 62, left: 54, right: 54 };
const CONTENT_WIDTH = PAGE.width - MARGIN.left - MARGIN.right;

const COLORS = {
  ink: '#0B1020',
  body: '#2B3350',
  muted: '#5A6480',
  border: '#DFE3EE',
  surface: '#F6F7FB',
  violet: '#5844D8',
  cyan: '#0E7490',
  excellent: '#0F9D6E',
  good: '#0E9BB8',
  fair: '#C77700',
  poor: '#DB6B10',
  critical: '#D0342C',
  white: '#FFFFFF',
} as const;

function scoreColor(score: number): string {
  if (score >= 85) return COLORS.excellent;
  if (score >= 70) return COLORS.good;
  if (score >= 55) return COLORS.fair;
  if (score >= 35) return COLORS.poor;
  return COLORS.critical;
}

type Doc = InstanceType<typeof PDFDocument>;

interface RenderContext {
  doc: Doc;
  data: ReportData;
  brandName: string;
  footerNote: string;
}

/**
 * Generate the full PDF and resolve with the complete buffer.
 */
export async function generateReportPdf(
  data: ReportData,
  options: { footerNote?: string } = {},
): Promise<Buffer> {
  const doc = new PDFDocument({
    size: 'A4',
    margins: MARGIN,
    bufferPages: true,
    autoFirstPage: false,
    info: {
      Title: `AI Visibility Audit — ${data.businessName}`,
      Author: data.branding.whiteLabel && data.branding.companyName ? data.branding.companyName : 'RankInAI',
      Subject: 'AI Visibility and Generative Engine Optimization audit report',
      Creator: 'RankInAI',
      Keywords: 'AI visibility, GEO, generative engine optimization, audit',
    },
  });

  const chunks: Buffer[] = [];
  doc.on('data', (chunk: Buffer) => chunks.push(chunk));

  const finished = new Promise<Buffer>((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  const brandName =
    data.branding.whiteLabel && data.branding.companyName ? data.branding.companyName : 'RankInAI';

  const ctx: RenderContext = {
    doc,
    data,
    brandName,
    footerNote:
      options.footerNote ?? 'Generated by RankInAI — AI visibility and GEO audit platform.',
  };

  renderCover(ctx);
  renderExecutiveSummary(ctx);
  renderCategoryScores(ctx);
  renderStrengthsWeaknesses(ctx);
  renderFindings(ctx);
  renderCompetitors(ctx);
  renderActionPlan(ctx);
  renderPages(ctx);
  renderMethodology(ctx);
  renderLimitations(ctx);

  paintPageFurniture(ctx);

  doc.end();
  return finished;
}

/* -------------------------------------------------------------------------- */
/* Layout helpers                                                             */
/* -------------------------------------------------------------------------- */

function newPage(doc: Doc) {
  doc.addPage({ size: 'A4', margins: MARGIN });
  doc.y = MARGIN.top;
}

/** Ensure `needed` points remain before the footer, otherwise break the page. */
function ensureSpace(doc: Doc, needed: number) {
  if (doc.y + needed > PAGE.height - MARGIN.bottom) {
    newPage(doc);
  }
}

function sectionHeading(doc: Doc, title: string, opts: { newPage?: boolean } = {}) {
  if (opts.newPage) newPage(doc);
  else ensureSpace(doc, 70);

  doc
    .fillColor(COLORS.ink)
    .font('Helvetica-Bold')
    .fontSize(15)
    .text(title, MARGIN.left, doc.y, { width: CONTENT_WIDTH });

  const y = doc.y + 6;
  doc
    .moveTo(MARGIN.left, y)
    .lineTo(MARGIN.left + CONTENT_WIDTH, y)
    .lineWidth(1)
    .strokeColor(COLORS.violet)
    .stroke();

  doc.y = y + 14;
}

function paragraph(
  doc: Doc,
  text: string,
  opts: { size?: number; color?: string; font?: string; gap?: number; indent?: number } = {},
) {
  const size = opts.size ?? 9.5;
  const width = CONTENT_WIDTH - (opts.indent ?? 0);
  const height = doc.font(opts.font ?? 'Helvetica').fontSize(size).heightOfString(text, { width });

  ensureSpace(doc, height + 6);

  doc
    .font(opts.font ?? 'Helvetica')
    .fontSize(size)
    .fillColor(opts.color ?? COLORS.body)
    .text(text, MARGIN.left + (opts.indent ?? 0), doc.y, { width, align: 'left' });

  doc.y += opts.gap ?? 8;
}

function labelValue(doc: Doc, label: string, value: string, x: number, y: number, width: number) {
  doc.font('Helvetica').fontSize(7.5).fillColor(COLORS.muted).text(label.toUpperCase(), x, y, { width });
  doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.ink).text(value, x, y + 11, { width });
}

/** Horizontal score bar. */
function scoreBar(doc: Doc, x: number, y: number, width: number, score: number, available = true) {
  const height = 6;
  doc.roundedRect(x, y, width, height, 3).fillColor(COLORS.border).fill();
  if (available && score > 0) {
    doc
      .roundedRect(x, y, Math.max(3, (width * Math.max(0, Math.min(100, score))) / 100), height, 3)
      .fillColor(scoreColor(score))
      .fill();
  }
}

function bulletList(doc: Doc, items: string[], opts: { color?: string } = {}) {
  for (const item of items) {
    const height = doc.font('Helvetica').fontSize(9.5).heightOfString(item, {
      width: CONTENT_WIDTH - 14,
    });
    ensureSpace(doc, height + 8);

    doc
      .circle(MARGIN.left + 3, doc.y + 4.5, 1.8)
      .fillColor(opts.color ?? COLORS.violet)
      .fill();

    doc
      .font('Helvetica')
      .fontSize(9.5)
      .fillColor(COLORS.body)
      .text(item, MARGIN.left + 14, doc.y, { width: CONTENT_WIDTH - 14 });

    doc.y += 6;
  }
}

/* -------------------------------------------------------------------------- */
/* 1. Cover                                                                    */
/* -------------------------------------------------------------------------- */

function renderCover({ doc, data, brandName }: RenderContext) {
  newPage(doc);

  // Dark header band.
  doc.rect(0, 0, PAGE.width, 232).fillColor(COLORS.ink).fill();

  // Wordmark (drawn, not an image, so no external asset is required).
  doc.font('Helvetica-Bold').fontSize(17).fillColor(COLORS.white).text(brandName, MARGIN.left, 48);

  doc
    .font('Helvetica')
    .fontSize(8)
    .fillColor('#A3ADC9')
    .text('AI VISIBILITY & GEO AUDIT REPORT', MARGIN.left, 72, { characterSpacing: 1.6 });

  doc
    .font('Helvetica-Bold')
    .fontSize(25)
    .fillColor(COLORS.white)
    .text(data.businessName, MARGIN.left, 108, { width: CONTENT_WIDTH });

  doc
    .font('Helvetica')
    .fontSize(10)
    .fillColor('#A3ADC9')
    .text(data.websiteUrl, MARGIN.left, doc.y + 4, { width: CONTENT_WIDTH });

  if (data.isDemo) {
    doc
      .roundedRect(PAGE.width - MARGIN.right - 120, 44, 120, 22, 5)
      .fillColor('#F59E0B')
      .fill();
    doc
      .font('Helvetica-Bold')
      .fontSize(9)
      .fillColor('#3A2A05')
      .text('DEMO DATA', PAGE.width - MARGIN.right - 120, 51, { width: 120, align: 'center' });
  }

  // Metadata strip.
  const metaY = 178;
  const colWidth = CONTENT_WIDTH / 4;
  const meta: Array<[string, string]> = [
    ['Audit date', formatDate(data.auditDate, 'long')],
    ['Pages analyzed', String(data.pagesCrawled)],
    ['Industry', data.industry ?? 'Not specified'],
    ['Target market', data.targetCountry],
  ];
  meta.forEach(([label, value], index) => {
    const x = MARGIN.left + colWidth * index;
    doc.font('Helvetica').fontSize(7).fillColor('#8792AE').text(label.toUpperCase(), x, metaY, {
      width: colWidth - 8,
      characterSpacing: 0.8,
    });
    doc
      .font('Helvetica-Bold')
      .fontSize(9.5)
      .fillColor(COLORS.white)
      .text(value, x, metaY + 12, { width: colWidth - 8 });
  });

  // Score block.
  doc.y = 272;
  const boxY = doc.y;
  doc
    .roundedRect(MARGIN.left, boxY, CONTENT_WIDTH, 132, 8)
    .fillColor(COLORS.surface)
    .fill()
    .roundedRect(MARGIN.left, boxY, CONTENT_WIDTH, 132, 8)
    .lineWidth(1)
    .strokeColor(COLORS.border)
    .stroke();

  // Score gauge drawn with arcs.
  const cx = MARGIN.left + 78;
  const cy = boxY + 66;
  const radius = 42;
  doc.circle(cx, cy, radius).lineWidth(10).strokeColor(COLORS.border).stroke();

  const fraction = Math.max(0, Math.min(100, data.overallScore)) / 100;
  if (fraction > 0) {
    const start = -Math.PI / 2;
    const end = start + fraction * Math.PI * 2;
    doc.save();
    doc.lineWidth(10).strokeColor(scoreColor(data.overallScore)).lineCap('round');
    // Approximate the arc with short segments — reliable across viewers.
    const steps = Math.max(2, Math.ceil(fraction * 60));
    doc.moveTo(cx + radius * Math.cos(start), cy + radius * Math.sin(start));
    for (let i = 1; i <= steps; i += 1) {
      const angle = start + ((end - start) * i) / steps;
      doc.lineTo(cx + radius * Math.cos(angle), cy + radius * Math.sin(angle));
    }
    doc.stroke();
    doc.restore();
  }

  doc
    .font('Helvetica-Bold')
    .fontSize(26)
    .fillColor(scoreColor(data.overallScore))
    .text(String(data.overallScore), cx - 40, cy - 16, { width: 80, align: 'center' });
  doc
    .font('Helvetica')
    .fontSize(8)
    .fillColor(COLORS.muted)
    .text('out of 100', cx - 40, cy + 13, { width: 80, align: 'center' });

  const textX = MARGIN.left + 154;
  const textWidth = CONTENT_WIDTH - 168;
  doc
    .font('Helvetica-Bold')
    .fontSize(12)
    .fillColor(COLORS.ink)
    .text(
      `Overall AI Visibility Score: ${data.overallScore}/100 (${scoreBandLabel(data.overallScore)})`,
      textX,
      boxY + 24,
      { width: textWidth },
    );
  doc
    .font('Helvetica')
    .fontSize(9)
    .fillColor(COLORS.body)
    .text(overallScoreInterpretation(data.overallScore), textX, doc.y + 5, { width: textWidth });

  if (data.previousScore != null) {
    const delta = data.overallScore - data.previousScore;
    doc
      .font('Helvetica-Bold')
      .fontSize(8.5)
      .fillColor(delta >= 0 ? COLORS.excellent : COLORS.critical)
      .text(
        `Previous audit: ${data.previousScore} (${delta >= 0 ? '+' : ''}${delta})`,
        textX,
        doc.y + 6,
        { width: textWidth },
      );
  }

  doc.y = boxY + 152;

  if (data.isDemo) {
    doc
      .roundedRect(MARGIN.left, doc.y, CONTENT_WIDTH, 52, 6)
      .fillColor('#FDF3E0')
      .fill()
      .roundedRect(MARGIN.left, doc.y, CONTENT_WIDTH, 52, 6)
      .lineWidth(1)
      .strokeColor('#E7B85C')
      .stroke();
    doc
      .font('Helvetica-Bold')
      .fontSize(9)
      .fillColor('#7A5200')
      .text('DEMONSTRATION DATA', MARGIN.left + 12, doc.y + 10, { width: CONTENT_WIDTH - 24 });
    doc
      .font('Helvetica')
      .fontSize(8.5)
      .fillColor('#7A5200')
      .text(
        `Every figure in this report is fictional and was created for product demonstration. ${data.businessName} is not a real company and no website was audited to produce these results.`,
        MARGIN.left + 12,
        doc.y + 2,
        { width: CONTENT_WIDTH - 24 },
      );
    doc.y += 26;
  }

  doc.y = Math.max(doc.y, 480);

  // Contents.
  doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.ink).text('Contents', MARGIN.left, doc.y);
  doc.y += 8;
  const contents = [
    '1. Executive summary',
    '2. Category scores',
    '3. Key strengths and critical weaknesses',
    '4. Detailed findings by category',
    '5. Competitor comparison',
    '6. Prioritized action plan',
    '7. Page-by-page observations',
    '8. Methodology',
    '9. Limitations and disclaimer',
  ];
  for (const line of contents) {
    doc.font('Helvetica').fontSize(9).fillColor(COLORS.body).text(line, MARGIN.left + 6, doc.y);
    doc.y += 3;
  }
}

/* -------------------------------------------------------------------------- */
/* 2. Executive summary                                                        */
/* -------------------------------------------------------------------------- */

function renderExecutiveSummary(ctx: RenderContext) {
  const { doc, data } = ctx;
  sectionHeading(doc, '1. Executive summary', { newPage: true });
  paragraph(doc, data.executiveSummary, { size: 10, gap: 12 });

  if (data.llmEnhanced) {
    paragraph(
      doc,
      `This summary was rewritten for clarity by ${data.llmModel ?? 'an AI model'} on ${formatDate(
        data.llmGeneratedAt,
        'datetime',
      )}. Scores and evidence are computed by the rule-based audit engine and were not altered.`,
      { size: 8, color: COLORS.muted, gap: 10 },
    );
  }

  const rows: Array<[string, string]> = [
    ['Business', data.businessName],
    ['Website', data.websiteUrl],
    ['Pages crawled', `${data.pagesCrawled} of up to ${data.pageLimit}`],
    ['Findings recorded', String(data.findings.length)],
    ['Recommendations', String(data.recommendations.length)],
    ['Competitors compared', String(data.competitors.filter((c) => c.overallScore != null).length)],
  ];

  ensureSpace(doc, rows.length * 18 + 20);
  const tableY = doc.y;
  doc.roundedRect(MARGIN.left, tableY, CONTENT_WIDTH, rows.length * 18 + 12, 6).fillColor(COLORS.surface).fill();

  rows.forEach(([label, value], index) => {
    const y = tableY + 8 + index * 18;
    doc.font('Helvetica').fontSize(9).fillColor(COLORS.muted).text(label, MARGIN.left + 12, y, {
      width: 150,
    });
    doc
      .font('Helvetica-Bold')
      .fontSize(9)
      .fillColor(COLORS.ink)
      .text(value, MARGIN.left + 168, y, { width: CONTENT_WIDTH - 180 });
  });

  doc.y = tableY + rows.length * 18 + 24;
}

/* -------------------------------------------------------------------------- */
/* 3. Category scores                                                          */
/* -------------------------------------------------------------------------- */

function renderCategoryScores(ctx: RenderContext) {
  const { doc, data } = ctx;
  sectionHeading(doc, '2. Category scores');

  for (const category of data.categories) {
    const summaryHeight = doc.font('Helvetica').fontSize(8.5).heightOfString(category.summary, {
      width: CONTENT_WIDTH - 24,
    });
    const blockHeight = 46 + summaryHeight;
    ensureSpace(doc, blockHeight + 10);

    const y = doc.y;
    doc
      .roundedRect(MARGIN.left, y, CONTENT_WIDTH, blockHeight, 6)
      .lineWidth(1)
      .strokeColor(COLORS.border)
      .stroke();

    doc
      .font('Helvetica-Bold')
      .fontSize(10)
      .fillColor(COLORS.ink)
      .text(category.label, MARGIN.left + 12, y + 10, { width: CONTENT_WIDTH - 90 });

    doc
      .font('Helvetica-Bold')
      .fontSize(14)
      .fillColor(category.available ? scoreColor(category.score) : COLORS.muted)
      .text(
        category.available ? String(category.score) : '—',
        PAGE.width - MARGIN.right - 60,
        y + 8,
        { width: 48, align: 'right' },
      );

    doc
      .font('Helvetica')
      .fontSize(7.5)
      .fillColor(COLORS.muted)
      .text(
        `${Math.round(category.effectiveWeight * 100)}% weight`,
        PAGE.width - MARGIN.right - 60,
        y + 25,
        { width: 48, align: 'right' },
      );

    scoreBar(doc, MARGIN.left + 12, y + 28, CONTENT_WIDTH - 90, category.score, category.available);

    doc
      .font('Helvetica')
      .fontSize(8.5)
      .fillColor(COLORS.body)
      .text(category.summary, MARGIN.left + 12, y + 40, { width: CONTENT_WIDTH - 24 });

    doc.y = y + blockHeight + 8;
  }
}

/* -------------------------------------------------------------------------- */
/* 4. Strengths and weaknesses                                                 */
/* -------------------------------------------------------------------------- */

function renderStrengthsWeaknesses(ctx: RenderContext) {
  const { doc, data } = ctx;
  sectionHeading(doc, '3. Key strengths and critical weaknesses');

  doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.excellent).text('Key strengths', MARGIN.left, doc.y);
  doc.y += 6;
  bulletList(
    doc,
    data.strengths.length > 0
      ? data.strengths
      : ['No checks passed with enough weight to be listed as a headline strength.'],
    { color: COLORS.excellent },
  );

  doc.y += 6;
  doc
    .font('Helvetica-Bold')
    .fontSize(10)
    .fillColor(COLORS.critical)
    .text('Critical weaknesses', MARGIN.left, doc.y);
  doc.y += 6;
  bulletList(
    doc,
    data.weaknesses.length > 0
      ? data.weaknesses
      : ['No failing checks were found. Remaining opportunities are refinements.'],
    { color: COLORS.critical },
  );
  doc.y += 6;
}

/* -------------------------------------------------------------------------- */
/* 5. Findings                                                                 */
/* -------------------------------------------------------------------------- */

function renderFindings(ctx: RenderContext) {
  const { doc, data } = ctx;
  sectionHeading(doc, '4. Detailed findings by category', { newPage: true });

  for (const category of data.categories.filter((c) => c.available)) {
    const findings = data.findings.filter((f) => f.category === category.category);
    if (findings.length === 0) continue;

    ensureSpace(doc, 60);
    doc
      .font('Helvetica-Bold')
      .fontSize(11.5)
      .fillColor(COLORS.violet)
      .text(`${category.label} — ${category.score}/100`, MARGIN.left, doc.y);
    doc.y += 8;

    for (const finding of findings) {
      renderFinding(ctx, finding);
    }
    doc.y += 6;
  }
}

function renderFinding(ctx: RenderContext, finding: ReportData['findings'][number]) {
  const { doc } = ctx;

  const explanationHeight = doc.font('Helvetica').fontSize(8.5).heightOfString(finding.explanation, {
    width: CONTENT_WIDTH - 20,
  });
  const actionHeight =
    finding.status === 'PASS'
      ? 0
      : doc.font('Helvetica').fontSize(8.5).heightOfString(finding.recommendedAction, {
          width: CONTENT_WIDTH - 20,
        }) + 18;

  const evidenceLines = evidenceSummary(finding.evidence);
  const evidenceHeight =
    evidenceLines.length > 0
      ? doc.font('Helvetica').fontSize(7.5).heightOfString(evidenceLines.join('\n'), {
          width: CONTENT_WIDTH - 20,
        }) + 14
      : 0;

  const total = 34 + explanationHeight + actionHeight + evidenceHeight;
  ensureSpace(doc, total + 12);

  const y = doc.y;
  const accent =
    finding.status === 'PASS'
      ? COLORS.excellent
      : finding.status === 'FAIL'
        ? COLORS.critical
        : finding.status === 'WARN'
          ? COLORS.fair
          : COLORS.cyan;

  // Left accent rule.
  doc.rect(MARGIN.left, y, 2.5, total).fillColor(accent).fill();

  doc
    .font('Helvetica-Bold')
    .fontSize(9.5)
    .fillColor(COLORS.ink)
    .text(finding.title, MARGIN.left + 10, y, { width: CONTENT_WIDTH - 110 });

  doc
    .font('Helvetica-Bold')
    .fontSize(7.5)
    .fillColor(accent)
    .text(SEVERITY_LABELS[finding.severity].toUpperCase(), PAGE.width - MARGIN.right - 92, y + 1, {
      width: 92,
      align: 'right',
      characterSpacing: 0.5,
    });

  doc
    .font('Helvetica')
    .fontSize(7)
    .fillColor(COLORS.muted)
    .text(finding.checkId, MARGIN.left + 10, y + 13, { width: CONTENT_WIDTH - 110 });

  doc
    .font('Helvetica')
    .fontSize(8.5)
    .fillColor(COLORS.body)
    .text(finding.explanation, MARGIN.left + 10, y + 24, { width: CONTENT_WIDTH - 20 });

  let cursor = y + 24 + explanationHeight + 6;

  if (finding.status !== 'PASS') {
    doc
      .font('Helvetica-Bold')
      .fontSize(7.5)
      .fillColor(COLORS.muted)
      .text('RECOMMENDED ACTION', MARGIN.left + 10, cursor, { characterSpacing: 0.5 });
    cursor += 10;
    doc
      .font('Helvetica')
      .fontSize(8.5)
      .fillColor(COLORS.ink)
      .text(finding.recommendedAction, MARGIN.left + 10, cursor, { width: CONTENT_WIDTH - 20 });
    cursor = doc.y + 4;
    doc
      .font('Helvetica')
      .fontSize(7.5)
      .fillColor(COLORS.muted)
      .text(
        `Effort: ${finding.effort.toLowerCase()}   ·   Impact: ${finding.impact.toLowerCase()}`,
        MARGIN.left + 10,
        cursor,
      );
    cursor += 12;
  }

  if (evidenceLines.length > 0) {
    doc
      .font('Helvetica-Bold')
      .fontSize(7.5)
      .fillColor(COLORS.muted)
      .text('EVIDENCE OBSERVED', MARGIN.left + 10, cursor, { characterSpacing: 0.5 });
    cursor += 10;
    doc
      .font('Helvetica')
      .fontSize(7.5)
      .fillColor(COLORS.body)
      .text(evidenceLines.join('\n'), MARGIN.left + 10, cursor, { width: CONTENT_WIDTH - 20 });
    cursor = doc.y + 4;
  }

  doc.y = Math.max(cursor, y + total) + 8;
}

function evidenceSummary(evidence: Record<string, unknown>): string[] {
  return Object.entries(evidence ?? {})
    .filter(([, value]) => value !== null && value !== undefined && value !== '')
    .slice(0, 8)
    .map(([key, value]) => `${key}: ${formatEvidence(value)}`);
}

function formatEvidence(value: unknown): string {
  if (typeof value === 'boolean') return value ? 'yes' : 'no';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'string') return value.length > 160 ? `${value.slice(0, 160)}…` : value;
  if (Array.isArray(value)) {
    if (value.length === 0) return 'none';
    const rendered = value
      .slice(0, 5)
      .map((v) => (typeof v === 'object' ? JSON.stringify(v) : String(v)))
      .join(', ');
    return rendered.length > 200 ? `${rendered.slice(0, 200)}…` : rendered;
  }
  const json = JSON.stringify(value);
  return json.length > 200 ? `${json.slice(0, 200)}…` : json;
}

/* -------------------------------------------------------------------------- */
/* 6. Competitors                                                              */
/* -------------------------------------------------------------------------- */

function renderCompetitors(ctx: RenderContext) {
  const { doc, data } = ctx;
  sectionHeading(doc, '5. Competitor comparison', { newPage: true });

  if (data.competitors.length === 0) {
    paragraph(
      doc,
      'No competitor was supplied for this audit, so Competitive Visibility was marked unavailable and its 5% weight was redistributed across the other six categories. Add a competitor URL when you re-run this audit to see the comparison.',
    );
    return;
  }

  paragraph(
    doc,
    'Competitor scores are derived from a single public homepage fetch, not a full crawl. They compare homepage-level signals only.',
    { size: 8.5, color: COLORS.muted },
  );

  const analyzed = data.competitors.filter((c) => c.overallScore != null);
  ensureSpace(doc, (analyzed.length + 1) * 26 + 16);

  const rows: Array<{ label: string; score: number; bold: boolean }> = [
    { label: `${data.businessName} (you)`, score: data.overallScore, bold: true },
    ...analyzed.map((c) => ({
      label: c.name ?? c.url,
      score: c.overallScore ?? 0,
      bold: false,
    })),
  ];

  for (const row of rows) {
    ensureSpace(doc, 26);
    doc
      .font(row.bold ? 'Helvetica-Bold' : 'Helvetica')
      .fontSize(9)
      .fillColor(COLORS.ink)
      .text(row.label, MARGIN.left, doc.y, { width: CONTENT_WIDTH - 44, ellipsis: true });
    doc
      .font('Helvetica-Bold')
      .fontSize(9)
      .fillColor(scoreColor(row.score))
      .text(String(row.score), PAGE.width - MARGIN.right - 34, doc.y - 11, {
        width: 34,
        align: 'right',
      });
    scoreBar(doc, MARGIN.left, doc.y + 2, CONTENT_WIDTH - 44, row.score);
    doc.y += 16;
  }

  doc.y += 8;

  for (const competitor of data.competitors) {
    ensureSpace(doc, 90);
    doc
      .font('Helvetica-Bold')
      .fontSize(10)
      .fillColor(COLORS.ink)
      .text(competitor.name ?? 'Competitor', MARGIN.left, doc.y, { width: CONTENT_WIDTH });
    doc.font('Helvetica').fontSize(8).fillColor(COLORS.muted).text(competitor.url, MARGIN.left, doc.y + 1);
    doc.y += 8;

    if (competitor.error) {
      paragraph(doc, competitor.error, { size: 8.5, color: COLORS.muted });
      continue;
    }

    if (competitor.highlights.length > 0) {
      doc
        .font('Helvetica-Bold')
        .fontSize(8)
        .fillColor(COLORS.excellent)
        .text('WHAT THEY DO WELL', MARGIN.left, doc.y, { characterSpacing: 0.5 });
      doc.y += 4;
      bulletList(doc, competitor.highlights, { color: COLORS.excellent });
    }

    if (competitor.gaps.length > 0) {
      doc
        .font('Helvetica-Bold')
        .fontSize(8)
        .fillColor(COLORS.fair)
        .text('WHERE THEY ARE WEAK', MARGIN.left, doc.y, { characterSpacing: 0.5 });
      doc.y += 4;
      bulletList(doc, competitor.gaps, { color: COLORS.fair });
    }

    doc.y += 8;
  }
}

/* -------------------------------------------------------------------------- */
/* 7. Action plan                                                              */
/* -------------------------------------------------------------------------- */

function renderActionPlan(ctx: RenderContext) {
  const { doc, data } = ctx;
  sectionHeading(doc, '6. Prioritized action plan', { newPage: true });

  if (data.recommendations.length === 0) {
    paragraph(
      doc,
      'No failing or partial checks were found. There is nothing in the action plan for this audit — re-run it after your next round of content changes to confirm the score holds.',
    );
    return;
  }

  const groups = [
    { key: 'DO_FIRST' as const, color: COLORS.critical },
    { key: 'NEXT_30_DAYS' as const, color: COLORS.fair },
    { key: 'LONGER_TERM' as const, color: COLORS.cyan },
  ];

  for (const group of groups) {
    const items = data.recommendations.filter((r) => r.horizon === group.key);
    if (items.length === 0) continue;

    ensureSpace(doc, 44);
    const y = doc.y;
    doc.roundedRect(MARGIN.left, y, CONTENT_WIDTH, 24, 5).fillColor(group.color).fill();
    doc
      .font('Helvetica-Bold')
      .fontSize(10)
      .fillColor(COLORS.white)
      .text(
        `${HORIZON_LABELS[group.key]} — ${items.length} ${items.length === 1 ? 'action' : 'actions'}`,
        MARGIN.left + 12,
        y + 7,
      );
    doc.y = y + 34;

    for (const rec of items) {
      renderRecommendation(ctx, rec);
    }
    doc.y += 6;
  }
}

function renderRecommendation(ctx: RenderContext, rec: ReportData['recommendations'][number]) {
  const { doc } = ctx;

  ensureSpace(doc, 110);

  doc
    .font('Helvetica-Bold')
    .fontSize(10)
    .fillColor(COLORS.ink)
    .text(`${rec.priority}. ${rec.title}`, MARGIN.left, doc.y, { width: CONTENT_WIDTH });
  doc.y += 2;

  doc
    .font('Helvetica')
    .fontSize(7.5)
    .fillColor(COLORS.muted)
    .text(
      `${rec.categoryLabel}   ·   ${rec.impact.toLowerCase()} impact   ·   ${rec.effort.toLowerCase()} effort`,
      MARGIN.left,
      doc.y,
    );
  doc.y += 8;

  fieldBlock(doc, 'WHY IT MATTERS', rec.whyItMatters);
  fieldBlock(doc, 'EXACT RECOMMENDED CHANGE', rec.recommendedChange);

  if (rec.exampleImplementation) {
    const height = doc.font('Courier').fontSize(7.5).heightOfString(rec.exampleImplementation, {
      width: CONTENT_WIDTH - 20,
    });
    ensureSpace(doc, height + 26);

    doc
      .font('Helvetica-Bold')
      .fontSize(7.5)
      .fillColor(COLORS.muted)
      .text('EXAMPLE IMPLEMENTATION', MARGIN.left, doc.y, { characterSpacing: 0.5 });
    doc.y += 8;

    const boxY = doc.y;
    doc.roundedRect(MARGIN.left, boxY, CONTENT_WIDTH, height + 14, 4).fillColor(COLORS.surface).fill();
    doc
      .font('Courier')
      .fontSize(7.5)
      .fillColor(COLORS.body)
      .text(rec.exampleImplementation, MARGIN.left + 10, boxY + 7, { width: CONTENT_WIDTH - 20 });
    doc.y = boxY + height + 20;
  }

  fieldBlock(doc, 'EXPECTED IMPACT', rec.expectedImpact);

  doc.y += 6;
  doc
    .moveTo(MARGIN.left, doc.y)
    .lineTo(MARGIN.left + CONTENT_WIDTH, doc.y)
    .lineWidth(0.5)
    .strokeColor(COLORS.border)
    .stroke();
  doc.y += 10;
}

function fieldBlock(doc: Doc, label: string, value: string) {
  const height = doc.font('Helvetica').fontSize(8.5).heightOfString(value, { width: CONTENT_WIDTH });
  ensureSpace(doc, height + 18);

  doc
    .font('Helvetica-Bold')
    .fontSize(7.5)
    .fillColor(COLORS.muted)
    .text(label, MARGIN.left, doc.y, { characterSpacing: 0.5 });
  doc.y += 8;
  doc.font('Helvetica').fontSize(8.5).fillColor(COLORS.body).text(value, MARGIN.left, doc.y, {
    width: CONTENT_WIDTH,
  });
  doc.y += 8;
}

/* -------------------------------------------------------------------------- */
/* 8. Pages                                                                    */
/* -------------------------------------------------------------------------- */

function renderPages(ctx: RenderContext) {
  const { doc, data } = ctx;
  sectionHeading(doc, '7. Page-by-page observations', { newPage: true });

  const columns = [
    { label: 'Page', width: 210 },
    { label: 'Status', width: 46 },
    { label: 'Words', width: 46 },
    { label: 'Schema', width: 125 },
    { label: 'Role', width: 60 },
  ];

  const drawHeader = () => {
    const y = doc.y;
    doc.rect(MARGIN.left, y, CONTENT_WIDTH, 20).fillColor(COLORS.surface).fill();
    let x = MARGIN.left + 8;
    for (const column of columns) {
      doc.font('Helvetica-Bold').fontSize(7.5).fillColor(COLORS.muted).text(column.label.toUpperCase(), x, y + 6, {
        width: column.width - 8,
        characterSpacing: 0.5,
      });
      x += column.width;
    }
    doc.y = y + 24;
  };

  drawHeader();

  for (const page of data.pages) {
    const label = page.title ?? page.url;
    const labelHeight = doc.font('Helvetica').fontSize(8).heightOfString(label, { width: 202 });
    const rowHeight = Math.max(24, labelHeight + 16);

    if (doc.y + rowHeight > PAGE.height - MARGIN.bottom) {
      newPage(doc);
      drawHeader();
    }

    const y = doc.y;
    let x = MARGIN.left + 8;

    doc.font('Helvetica').fontSize(8).fillColor(COLORS.ink).text(label, x, y, { width: 202 });
    doc
      .font('Helvetica')
      .fontSize(6.5)
      .fillColor(COLORS.muted)
      .text(page.url, x, doc.y, { width: 202, ellipsis: true });
    x += columns[0]!.width;

    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor(page.error ? COLORS.critical : COLORS.body)
      .text(page.statusCode != null ? String(page.statusCode) : '—', x, y, { width: 38 });
    x += columns[1]!.width;

    doc.font('Helvetica').fontSize(8).fillColor(COLORS.body).text(page.wordCount ? String(page.wordCount) : '—', x, y, {
      width: 38,
    });
    x += columns[2]!.width;

    doc
      .font('Helvetica')
      .fontSize(7.5)
      .fillColor(COLORS.body)
      .text(page.schemaTypes.length > 0 ? page.schemaTypes.slice(0, 3).join(', ') : 'none', x, y, {
        width: 117,
      });
    x += columns[3]!.width;

    doc
      .font('Helvetica')
      .fontSize(7.5)
      .fillColor(COLORS.muted)
      .text(page.role.replace(/_/g, ' ').toLowerCase(), x, y, { width: 54 });

    doc.y = y + rowHeight;
    doc
      .moveTo(MARGIN.left, doc.y - 4)
      .lineTo(MARGIN.left + CONTENT_WIDTH, doc.y - 4)
      .lineWidth(0.5)
      .strokeColor(COLORS.border)
      .stroke();
  }

  if (data.robotsSummary) {
    doc.y += 12;
    ensureSpace(doc, 80);
    doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.ink).text('Site-level files', MARGIN.left, doc.y);
    doc.y += 8;
    bulletList(doc, [
      `robots.txt: ${data.robotsSummary.found ? 'found' : 'not found'}`,
      `XML sitemap: ${
        data.robotsSummary.sitemapFound
          ? `found (${data.robotsSummary.sitemapUrlCount} URLs)`
          : 'not found'
      }`,
      `llms.txt: ${data.robotsSummary.llmsTxtFound ? 'found' : 'not found'}`,
      `AI crawlers blocked: ${
        data.robotsSummary.blockedAiAgents.length > 0
          ? data.robotsSummary.blockedAiAgents.join(', ')
          : 'none'
      }`,
    ]);
  }
}

/* -------------------------------------------------------------------------- */
/* 9-10. Methodology and limitations                                           */
/* -------------------------------------------------------------------------- */

function renderMethodology(ctx: RenderContext) {
  const { doc } = ctx;
  sectionHeading(doc, '8. Methodology', { newPage: true });

  for (const item of METHODOLOGY_SUMMARY) {
    ensureSpace(doc, 50);
    doc.font('Helvetica-Bold').fontSize(9.5).fillColor(COLORS.ink).text(item.heading, MARGIN.left, doc.y);
    doc.y += 4;
    paragraph(doc, item.body, { size: 8.5, gap: 10 });
  }
}

function renderLimitations(ctx: RenderContext) {
  const { doc } = ctx;
  sectionHeading(doc, '9. Limitations and disclaimer');
  bulletList(doc, REPORT_LIMITATIONS, { color: COLORS.cyan });
}

/* -------------------------------------------------------------------------- */
/* Page furniture (headers, footers, page numbers)                            */
/* -------------------------------------------------------------------------- */

function paintPageFurniture({ doc, data, brandName, footerNote }: RenderContext) {
  const range = doc.bufferedPageRange();

  for (let i = range.start; i < range.start + range.count; i += 1) {
    doc.switchToPage(i);

    const isCover = i === range.start;

    if (!isCover) {
      // Running header.
      doc
        .font('Helvetica')
        .fontSize(7.5)
        .fillColor(COLORS.muted)
        .text(`${brandName} — AI Visibility Audit`, MARGIN.left, 30, {
          width: CONTENT_WIDTH / 2,
          lineBreak: false,
        });
      doc
        .font('Helvetica')
        .fontSize(7.5)
        .fillColor(COLORS.muted)
        .text(data.businessName, MARGIN.left + CONTENT_WIDTH / 2, 30, {
          width: CONTENT_WIDTH / 2,
          align: 'right',
          lineBreak: false,
        });
      doc
        .moveTo(MARGIN.left, 43)
        .lineTo(MARGIN.left + CONTENT_WIDTH, 43)
        .lineWidth(0.5)
        .strokeColor(COLORS.border)
        .stroke();
    }

    // Footer.
    const footerY = PAGE.height - 42;
    doc
      .moveTo(MARGIN.left, footerY - 8)
      .lineTo(MARGIN.left + CONTENT_WIDTH, footerY - 8)
      .lineWidth(0.5)
      .strokeColor(COLORS.border)
      .stroke();

    const leftNote = data.isDemo
      ? 'DEMO DATA — fictional demonstration report'
      : data.branding.whiteLabel
        ? 'Powered by RankInAI'
        : footerNote;

    doc
      .font('Helvetica')
      .fontSize(7)
      .fillColor(data.isDemo ? COLORS.fair : COLORS.muted)
      .text(leftNote, MARGIN.left, footerY, { width: CONTENT_WIDTH - 70, lineBreak: false });

    doc
      .font('Helvetica')
      .fontSize(7)
      .fillColor(COLORS.muted)
      .text(`Page ${i - range.start + 1} of ${range.count}`, MARGIN.left + CONTENT_WIDTH - 70, footerY, {
        width: 70,
        align: 'right',
        lineBreak: false,
      });
  }

  // Leave the cursor on the last page so nothing is appended accidentally.
  doc.switchToPage(range.start + range.count - 1);
}
