import { writeFileSync } from 'node:fs';
import path from 'node:path';

/**
 * The one definition of the automated-test environment.
 *
 * Both test runners read it:
 *   - Vitest's integration setup loads `.env.test`
 *   - Playwright starts `next dev` with NODE_ENV=test, and Next reads
 *     `.env.test` ahead of `.env`
 *
 * That second point is the reason this file writes to disk rather than only
 * setting `process.env`. Next.js loads `.env` itself and lets the file win over
 * values already present in the environment, so passing settings through the
 * child process alone is not enough — the developer's `.env` would silently
 * point the application at the development database while the worker used the
 * test one. `.env.test` is regenerated on every run and git-ignored, so nothing
 * here is committed and a fresh clone needs no manual setup.
 *
 * Everything below is a throwaway local value. Real secrets never live here.
 */

export const E2E_PORT = Number(process.env.E2E_PORT ?? 3210);
export const E2E_BASE_URL = `http://127.0.0.1:${E2E_PORT}`;

/** The fixture website the crawler is allowed to reach, host *and* port. */
export const FIXTURE_ORIGIN = 'http://127.0.0.1:4321';

export const TEST_ENV = {
  NODE_ENV: 'test',
  DATABASE_URL:
    process.env.E2E_DATABASE_URL ?? 'postgresql://rankinai:rankinai@127.0.0.1:5432/rankinai_test',
  AUTH_SECRET: 'e2e-secret-value-long-enough-for-the-production-guard-abcdef',
  AUTH_TRUST_HOST: 'true',
  NEXT_PUBLIC_APP_URL: E2E_BASE_URL,
  SUPER_ADMIN_EMAIL: 'admin@rankinai.com',
  SUPER_ADMIN_SEED_PASSWORD: 'RankInAI-Dev-Admin-2026!',
  BILLING_TEST_MODE: 'true',
  EMAIL_PROVIDER: 'console',
  SEARCH_PROVIDER: 'none',
  // Host *and* port: `127.0.0.1` alone would expose every service on the
  // loopback interface — the database included — to the crawler.
  ALLOW_TEST_FIXTURE_HOST: '127.0.0.1:4321',
  TEST_FIXTURE_ORIGIN: FIXTURE_ORIGIN,
  CRAWL_DELAY_MS: '0',
  WORKER_POLL_INTERVAL_MS: '1000',
  NEXT_TELEMETRY_DISABLED: '1',
} as const;

export function writeTestEnvFile(): void {
  const lines = [
    '# Generated by tests/test-env.ts on every test run — do not edit, do not commit.',
    '# Throwaway local test values, not secrets.',
    ...Object.entries(TEST_ENV).map(([key, value]) => `${key}=${value}`),
  ];
  writeFileSync(path.join(process.cwd(), '.env.test'), `${lines.join('\n')}\n`, 'utf8');
}
