import type { Metadata } from 'next';
import Link from 'next/link';

import { Alert, Card } from '@/components/ui/primitives';
import { SystemSettingsForm } from '@/app/(admin)/admin/settings/settings-form';
import { requireAdmin } from '@/lib/auth/guards';
import { getSettings } from '@/lib/settings';
import { LEGAL_SLUGS, LEGAL_DOCUMENTS } from '@/lib/legal-content';

export const metadata: Metadata = {
  title: 'Admin — settings',
  robots: { index: false, follow: false },
};

export default async function AdminSettingsPage() {
  await requireAdmin();
  const settings = await getSettings();

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <header>
        <h1 className="text-2xl font-bold">System settings</h1>
        <p className="mt-1 text-sm text-[var(--muted-foreground)]">
          Operational toggles and copy that can be changed without a redeploy.
        </p>
      </header>

      <Alert tone="warning" title="Legal pages are software-generated templates">
        <p>
          The Terms of Service, Privacy Policy, Refund Policy, Cookie Policy and Acceptable Use
          Policy shipped with this platform are{' '}
          <strong>starting templates generated by software</strong>. They have not been reviewed by
          an attorney and do not constitute legal advice.
        </p>
        <p className="mt-2">
          Have each of them reviewed and adapted to your jurisdiction and business model before
          commercial launch. Review them at:{' '}
          {LEGAL_SLUGS.map((slug, index) => (
            <span key={slug}>
              <Link
                href={`/legal/${slug}`}
                className="text-[var(--accent)] underline underline-offset-4"
              >
                {LEGAL_DOCUMENTS[slug]?.title}
              </Link>
              {index < LEGAL_SLUGS.length - 1 ? ', ' : '.'}
            </span>
          ))}
        </p>
        <p className="mt-2 text-xs">
          The customer-facing template notice on those pages can be switched off below once you have
          replaced them with reviewed documents.
        </p>
      </Alert>

      <Card className="p-6">
        <SystemSettingsForm settings={settings} />
      </Card>
    </div>
  );
}
